### ISSUE TITLE
Audio player states 

### ISSUE THREAD

**Issue by KoopReynders** [julia-stevens/fix-the-flow-interactive-website#28]
Je kan nog veel states aan de audioplayer toevoegen.
Belangrijk is feedforward op de play button
En feedback op loading ?
En daarna feedforward als de button een pauze knop wordt ...

> Don’t worry about stating the obvious…the obvious almost never is.

**Comment by KoopReynders** [comment]
Dit is misschien een mooi voorbeeld, op een van de pagina's van radio1: 

![image](https://github.com/user-attachments/assets/e56dee32-acc9-4289-aa63-0e63cd2a69d5)

https://www.nporadio1.nl/fragmenten/de-taalstaat/9daaccf7-9c09-4e78-841b-b77d2d17170c/2024-12-07-ton-den-boon-over-het-stilleggen-van-de-verkiezing-van-woord-van-het-jaar

**Comment by julia-stevens** [comment]
Ik heb een aantal nieuwe schetsen gemaakt, met daarin het herontwerp van de player en nieuwe states

![image](https://github.com/user-attachments/assets/f55051f8-3785-4a2d-a80d-35321795f46b)

![image](https://github.com/user-attachments/assets/9768b2c3-8246-41d0-bdb4-cb7849dd4d55)

![image](https://github.com/user-attachments/assets/062311fe-f9e8-4c8c-8aaf-900d4cc02874)

**Comment by julia-stevens** [comment]
**Commit:** [5d8759e](https://github.com/julia-stevens/fix-the-flow-interactive-website/commit/5d8759e7141cbc0c1fdf1e6af307bb4378a64003)

* Loading animatie toegevoegd in CSS
* In JS wordt deze met een `addEventListener("click")` aangeroepen 
* Wanneer animatie eindigt, wordt deze class uit getoggled en nummer gestart met `playTrack()`
* Object `buttonLabelStates` toegevoegd met "Speel af, Laden en Pauzeer". Deze wordt op in de juiste functies gebruikt om de tekst onder play button aan te passen, bijvoorbeeld bij `loadTrack()`: 

```js
function loadingTrack() {
    if (isPlaying === false) { // als er niks afspeelt, start loading animatie
        buttonImage.classList.toggle("loadingTrack");
        buttonLabel.textContent = buttonLabelStates.loading;
    } else { // als er wel wat afspeelt, pauzeer nummer en verander afbeelding en button label state
        isPlaying = false;
        currentTrack.pause();
        buttonImage.classList.remove("pause-track");
        buttonImage.classList.add("play-track");
        buttonLabel.textContent = buttonLabelStates.start; 
    }
}
```

https://github.com/user-attachments/assets/d1cd7845-be3f-4940-81d8-247ea39c9116

@KoopReynders Wat vind je nu van de states? Geeft dit voldoende feedback/feedforward? Heb je nog aanvullingen?

**Comment by KoopReynders** [comment]
Heel mooi, dat ziet er profi uit! (handig ook dat filmpje) Mooi ook het text label en de hover met dat lijntje. Voelt als een geheel. 

Komen de loading lijntjes/het zonnetje, uit elementen van de huisstijl? Misschien dikte van de lijntjes consistent doorvoeren. 

Vrijdag testen !

**Comment by julia-stevens** [comment]
[5d8759e](https://github.com/julia-stevens/fix-the-flow-interactive-website/commit/5d8759e7141cbc0c1fdf1e6af307bb4378a64003)
